parameters:
    infinite_developers_base64.image_extension.class: InfiniteDevelopers\Base64Bundle\Twig\ImageExtension

services:
    infinite_developers_base64.image_extension:
        class: %infinite_developers_base64.image_extension.class%
        tags:
            - { name: twig.extension }